config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Redirect www traffic
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: { subdomain: 'www' }

  # Errors
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Authentication
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # Profile verification
  devise_scope :user do
    get 'user/verify', to: 'users/registrations#verify'
  end

  # Authenticated routes
  authenticated do
    # Defines the root path route ("/")
    root to: 'dashboard#index', as: :authenticated_root

    # Two factor authentication
    resource :two_factor_settings, except: %i[index show]
  end

  # Star Network views
  get 'dashboard', to: 'dashboard#index'

  # Admin routes
  authenticated :user, ->(user) { user.admin? } do
    # Sidekiq
    Sidekiq::Web.app_url = '/'
    mount Sidekiq::Web => '/sidekiq'
  end

  # Marketing
  get 'home', to: 'home#index'

  root to: 'home#index'
end

app/controllers/two_factor_settings_controller.rb
# frozen_string_literal: true

class TwoFactorSettingsController < ApplicationController
  before_action :add_two_factor_breadcrumb

  # @route GET /two_factor_settings/new (new_two_factor_settings)
  def new
    add_breadcrumb(name: 'Two Factor', path: new_two_factor_settings_path)

    if current_user.otp_required_for_login
      return redirect_to edit_user_registration_path, alert: 'Two Factor Authentication is already enabled.'
    end

    current_user.generate_two_factor_secret_if_missing!
  end

  # @route GET /two_factor_settings/edit (edit_two_factor_settings)
  def edit
    add_breadcrumb(name: 'Two Factor', path: edit_two_factor_settings_path)

    unless current_user.otp_required_for_login
      return redirect_to new_two_factor_settings_path, alert: 'Please enable two factor authentication first.'
    end

    if current_user.two_factor_backup_codes_generated?
      return redirect_to edit_user_registration_path, alert: 'You have already seen your backup codes.'
    end

    @backup_codes = current_user.generate_otp_backup_codes!
    current_user.save!
  end

  # @route POST /two_factor_settings (two_factor_settings)
  def create
    add_breadcrumb(name: 'Two Factor', path: new_two_factor_settings_path)

    return render :new, alert: 'Incorrect password' unless current_user.valid_password?(enable_2fa_params[:password])

    if current_user.validate_and_consume_otp!(enable_2fa_params[:code])
      current_user.enable_two_factor!

      redirect_to edit_two_factor_settings_path,
                  notice: 'Successfully enabled two factor authentication, please make note of your backup codes.'
    else
      render :new, alert: 'Incorrect Code'
    end
  end

  # @route DELETE /two_factor_settings (two_factor_settings)
  def destroy
    add_breadcrumb(name: 'Two Factor', path: edit_two_factor_settings_path)

    if current_user.disable_two_factor!
      redirect_to edit_user_registration_path, notice: 'Successfully disabled two factor authentication.'
    else
      redirect_back fallback_location: root_path, alert: 'Could not disable two factor authentication.'
    end
  end

  private
    def enable_2fa_params
      params.require(:two_fa).permit(:code, :password)
    end

    def add_two_factor_breadcrumb
      add_breadcrumb(name: 'User', path: edit_user_registration_path)
    end
end

app/views/two_factor_settings/edit.html.erb
<% content_for :title do %>
  Two Factor Authentication
<% end %>
<%= render(Layout::ContentFrameComponent.new) do %>
  <div class="grid grid-cols-1 sm:grid-cols-2">
    <div class="space-y-4 px-4 py-4 sm:p-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Backup Codes</h3>
      <p class="my-2 text-sm text-gray-500">
        Keep these backup codes safe in case you lose access to your authenticator app:
      </p>
      <div class="grid grid-cols-2 italic text-orange-700">
        <% @backup_codes.each_slice(2) do |(code1, code2)| %>
          <div><%= code1 %></div>
          <div><%= code2 %></div>
        <% end %>
      </div>
    </div>

    <div class="space-y-4 px-4 py-4 sm:p-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Two Factor Setup Complete</h3>
      <p class="my-2 text-sm text-gray-500">
        Two factor authentication has been successfully enabled.
      </p>
      <div>
        <%= render(Layout::ButtonComponent.new(text: 'Return to account settings', path: edit_user_registration_path)) %>
      </div>
    </div>
  </div>
<% end %>

app/views/two_factor_settings/new.html.erb
<% content_for :title do %>
  Two Factor Authentication
<% end %>

<%= render(Layout::ContentFrameComponent.new) do %>
  <div class="grid grid-cols-1 sm:grid-cols-2">
    <div class="space-y-4 px-4 py-4 sm:p-6">
      <h3 class="text-lg font-medium leading-6 text-gray-900">1. Scan QR Code</h3>
      <p class="my-2 text-sm text-gray-500">
        Please scan the below QR code using an OTP compatible app (such as 1Password or Authy).
      </p>
      <div>
        <%= qr_code_as_svg(current_user.two_factor_qr_code_uri) %>
      </div>
      <p class="my-2 text-sm text-gray-500">
        If you cannot scan, please enter the following code manually: <span class="italic text-orange-700">
          <%= current_user.otp_secret %></span>
      </p>
    </div>

    <%= simple_form_for(:two_fa, url: two_factor_settings_path, method: :post) do |f| %>
      <div class="space-y-4 px-4 py-4 sm:p-6">
        <h3 class="text-lg font-medium leading-6 text-gray-900">2. Confirm OTP Code</h3>

        <%= f.input :code, required: true, autofocus: true %>
        <%= f.input :password, hint: 'Enter your current password' %>

        <div class="text-right">
          <%= f.button :submit, 'Confirm and Enable Two Factor' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>